CREATE TABLE TB_COMMON_CODE
(
    GROUP_CODE                  VARCHAR2(10) NOT NULL,
    DETAIL_CODE                 VARCHAR2(50) NOT NULL,
    CODE_NAME                   VARCHAR2(50) NOT NULL,
    DISPLAY_ORDER               NUMBER(3),
    CONSTRAINT PK_COMMON_CODE PRIMARY KEY (GROUP_CODE, DETAIL_CODE)
);


INSERT INTO TB_COMMON_CODE ( GROUP_CODE, DETAIL_CODE, CODE_NAME, DISPLAY_ORDER) VALUES ('000100','JP','JAPAN',3);
INSERT INTO TB_COMMON_CODE ( GROUP_CODE, DETAIL_CODE, CODE_NAME, DISPLAY_ORDER) VALUES ('000100','KR','KOREA, REPUBLIC OF',1);
INSERT INTO TB_COMMON_CODE ( GROUP_CODE, DETAIL_CODE, CODE_NAME, DISPLAY_ORDER) VALUES ('000100','US','UNITED STATES OF AMERICA',2);
INSERT INTO TB_COMMON_CODE ( GROUP_CODE, DETAIL_CODE, CODE_NAME, DISPLAY_ORDER) VALUES ('000200','en','English',2);
INSERT INTO TB_COMMON_CODE ( GROUP_CODE, DETAIL_CODE, CODE_NAME, DISPLAY_ORDER) VALUES ('000200','ja','Japan',3);
INSERT INTO TB_COMMON_CODE ( GROUP_CODE, DETAIL_CODE, CODE_NAME, DISPLAY_ORDER) VALUES ('000200','ko','Korean',1);
INSERT INTO TB_COMMON_CODE ( GROUP_CODE, DETAIL_CODE, CODE_NAME, DISPLAY_ORDER) VALUES ('999999','000100','국가코드',1);
INSERT INTO TB_COMMON_CODE ( GROUP_CODE, DETAIL_CODE, CODE_NAME, DISPLAY_ORDER) VALUES ('999999','000200','언어코드',2);